### ISSUE TITLE
Does not accept -d or -H flags

### ISSUE THREAD

**Issue by bkazez** [joona/aws-es-curl#7]
I spent a few hours trying to debug why my index mappings weren't sticking. Turns out it's because the only way to get body info into the tool is via pipe, not the -d that is in all the ES docs, and even when I did that, the -H flags weren't accepted and therefore any json documents were rejected because of wrong encoding.

**Comment by piu28** [comment]
Facing the same issue. How can I pass the content type header then? I am trying to use -H. But no luck. Getting error: "Content-Type header is missing".

**Comment by kaibadash** [comment]
I fixed a problem of Content-Type header :)
https://github.com/joona/aws-es-curl/pull/10

**Comment by joona** [comment]
#10 and #11 are now included in the  release 1.0.7
